[package]
name = "softwarerenderer"
version = "0.1.0"
authors = ["James <44278296+JamesXM@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.2"